//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WfpBotConsole.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoReply {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoReply() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WfpBotConsole.Resources.AutoReply", typeof(AutoReply).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vno.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хуй на!.
        /// </summary>
        public static string а {
            get {
                return ResourceManager.GetString("а", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нага ебать! 🦵.
        /// </summary>
        public static string ага {
            get {
                return ResourceManager.GetString("ага", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вно.
        /// </summary>
        public static string го {
            get {
                return ResourceManager.GetString("го", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пизда!;Пидора еда!.
        /// </summary>
        public static string да {
            get {
                return ResourceManager.GetString("да", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤚🏿💩.
        /// </summary>
        public static string не {
            get {
                return ResourceManager.GetString("не", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пидора ответ!;Говна пакет!;Покукешай винегрет!.
        /// </summary>
        public static string нет {
            get {
                return ResourceManager.GetString("нет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Та нишо....
        /// </summary>
        public static string нушовы {
            get {
                return ResourceManager.GetString("нушовы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Та нишо....
        /// </summary>
        public static string нушотут {
            get {
                return ResourceManager.GetString("нушотут", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вилы ему в зад!.
        /// </summary>
        public static string пидор {
            get {
                return ResourceManager.GetString("пидор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джигурда! 🧔.
        /// </summary>
        public static string пизда {
            get {
                return ResourceManager.GetString("пизда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.
        /// </summary>
        public static string ф {
            get {
                return ResourceManager.GetString("ф", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хуй з&apos;їв нашо?.
        /// </summary>
        public static string шо {
            get {
                return ResourceManager.GetString("шо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Та нишо....
        /// </summary>
        public static string шовы {
            get {
                return ResourceManager.GetString("шовы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Та нишо....
        /// </summary>
        public static string шотут {
            get {
                return ResourceManager.GetString("шотут", resourceCulture);
            }
        }
    }
}
