//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WfpBotConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WfpBotConsole.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шо нада?.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Пидоры потеряшки:* {0}.
        /// </summary>
        internal static string MissedGames {
            get {
                return ResourceManager.GetString("MissedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опа, новый Пидор в игре! Поприветствуем @{0} !.
        /// </summary>
        internal static string NewPlayerAdded {
            get {
                return ResourceManager.GetString("NewPlayerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иииии *пидор дня* сегодня {0} !.
        /// </summary>
        internal static string NewWinner {
            get {
                return ResourceManager.GetString("NewWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Праздники!*.
        /// </summary>
        internal static string TodayHolidays {
            get {
                return ResourceManager.GetString("TodayHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторяю, *пидор* сегодня {0}  !.
        /// </summary>
        internal static string TodayWinnerAlreadySet {
            get {
                return ResourceManager.GetString("TodayWinnerAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куме, а чув як сьогодні {0} називають? *Піііііііііііііідор*.
        /// </summary>
        internal static string TodayWinnerAlreadySetUkr {
            get {
                return ResourceManager.GetString("TodayWinnerAlreadySetUkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ {0} пидоров месяца!*.
        /// </summary>
        internal static string TopMonthWinners {
            get {
                return ResourceManager.GetString("TopMonthWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среда мои чювачки!.
        /// </summary>
        internal static string WednesdayMyDudes {
            get {
                return ResourceManager.GetString("WednesdayMyDudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тащемта, он такой навсегда....
        /// </summary>
        internal static string WinnerForever {
            get {
                return ResourceManager.GetString("WinnerForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока не знаю, дай подумать. Скоро определим..
        /// </summary>
        internal static string WinnerNotSetYet {
            get {
                return ResourceManager.GetString("WinnerNotSetYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А вчера *пидором* был {0} !.
        /// </summary>
        internal static string YesterdayWinner {
            get {
                return ResourceManager.GetString("YesterdayWinner", resourceCulture);
            }
        }
    }
}
