// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using WfpBotConsole.Data;

namespace WfpBotConsole.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20210103130951_InitialCreate")]
	partial class InitialCreate
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "5.0.1");

			modelBuilder.Entity("WfpBotConsole.Models.GameResult", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<long>("ChatId")
						.HasColumnType("INTEGER");

					b.Property<DateTime>("PlayedAt")
						.HasColumnType("TEXT");

					b.Property<int>("UserId")
						.HasColumnType("INTEGER");

					b.Property<string>("UserName")
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("Results");
				});

			modelBuilder.Entity("WfpBotConsole.Models.Player", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<long>("ChatId")
						.HasColumnType("INTEGER");

					b.Property<int>("UserId")
						.HasColumnType("INTEGER");

					b.Property<string>("UserName")
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("Players");
				});
#pragma warning restore 612, 618
		}
	}
}
